kind: Service
apiVersion: v1
metadata:
  name: feed-service
  labels:
    app: feed-service
spec:
  type: NodePort
  selector:
    app: feed-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service-deployment
  labels:
    app: feed-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
      - name: feed-service
        imagePullPolicy: Always
        image: chetan253/feed-service
        ports:
        - containerPort: 8080
