kind: Service
apiVersion: v1
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
      # Port accessible inside cluster
    - port: 8081
      # Port to forward to inside the pod
      targetPort: 8081
      # Port accessible outside cluster 
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        imagePullPolicy: Always
        image: chetan253/api-gateway
        ports:
        - containerPort: 8081
