ind: Service
apiVersion: v1
metadata:
  name: user-mgmt-service
spec:
  type: NodePort
  selector:
    app: user-mgmt-service
  ports:
      # Port accessible inside cluster
    - port: 3001
      # Port to forward to inside the pod
      targetPort: 3000
      # Port accessible outside cluster
      nodePort: 30010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mgmt-service-deployment
  labels:
    app: user-mgmt-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mgmt-service
  template:
    metadata:
      labels:
        app: user-mgmt-service
    spec:
      containers:
      - name: user-mgmt-service
        imagePullPolicy: Always
        image: chetan253/user-mgmt-service
        ports:
        - containerPort: 3000
      restartPolicy: Always
