server:
  port: 8081
spring:
  application:
    name: zuulserver
zuul:
  routes:
    feed-service:
      path: /feed/**
      url: http://feed.service.consul:8080/
    news:
      path: /news/**
      url: http://news.service.consul:5000/
    users:
      path: /users/**
      url: http://users.service.consul:3000/
