server:
  port: 8081
spring:
  application:
    name: zuulserver
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  debug:
    request: true
  routes:
    feed-service:
      path: /feed/**
      url: http://feed-service:8080/
    news:
      path: /news/**
      url: http://news-service:5000/
    users:
      path: /users/**
      url: http://user-mgmt-service:3001/
